[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2"
    ]
build-backend = 'setuptools.build_meta'

[project]
name = "standard_evaluator"
description = "Project description"
readme = "README.md"
authors = [
    {name = "Joerg Gablonsky", email = "joerg.m.gablonsky@boeing.com"},
    {name = "Mark Bennett"},
    {name = "Micah Goldade"},
    {name = "Nathan Pitts"},
    {name = "Ben Link"},
    {name = "Colt Kirkpatrick"},
    {name = "Jeff Poskin"},
    {name = "Anjali Prasad"},
    {name = "Tyler Smith"},
    {name = "Mikel Woo"},
]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "numpy",
    "pandas",
    "pydantic>=2",
    "annotated-types",
    "numpydantic>=1.6.9",
    "openpyxl",
    "dask",
    "networkx",
    "openmdao",
    "json-numpy",
    "h5py",
    "h11>=0.16.0",
    "urllib3>=2.6.3",
]

dynamic = ["version", "scripts"]

[tool.setuptools_scm]
version_scheme = "post-release"

[project.optional-dependencies]
aviary = [
    "aviary",
    "dymos",
]
excel = [
    "pywin32; sys_platform == 'win32'",
]
test = [
    "pytest",
    "pytest-cov",
    "coverage",
    "hypothesis",
    "numdifftools",
]
dev = [
    # Copy test requirements below
    "pytest",
    "pytest-cov",
    "coverage",
    # Additional requirements to test
    "black",
    "flake8",
    "jupyter",
]
docs = [
    # Copy test and dev requirements below
    "pytest",
    "pytest-cov",
    "coverage",
    # Additional requirements to test
    "black",
    "flake8",
    # Additional requirements to test and dev
    "sphinx",
    "jupyter",
    "jupyterlab>=4.5.7",
    "autodocsumm",
    "pytest-cov",
    "sphinxcontrib-mermaid",
    "sphinx-rtd-theme",
    "jupyter_core",
    "myst-nb",
    
]

[tool.pytest.ini_options]
testpaths = "tests"
minversion = "6.0"
# log_cli_level = "INFO"
# log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
# log_cli_date_format = "%Y-%m-%d %H:%M:%S"
# log_cli = true